import type { Metadata } from "next";
import { SiteFooter } from "@/app/_landing/content";
import { SiteNav } from "@/app/_landing/site-nav";

export const metadata: Metadata = {
  title: "Terms of Service — Debrief by Whitecoat Prep",
  description: "Terms of service for Debrief, the voice-to-assessment platform for medical trainees.",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <SiteNav />

      <main
        id="main-content"
        className="mx-auto max-w-[720px] px-6 py-12 sm:py-16"
      >
        <div className="mb-10">
          <p className="mb-3 text-xs font-medium uppercase tracking-widest text-muted">
            Legal
          </p>
          <h1 className="font-[family-name:var(--font-display)] text-[2rem] leading-[1.2] text-foreground sm:text-[2.5rem]">
            Terms of Service
          </h1>
          <p className="mt-3 text-sm text-muted">
            Last updated: April 25, 2026.
          </p>
        </div>

        <div className="space-y-10 text-base leading-relaxed text-foreground">

          <section aria-labelledby="who-can-use">
            <h2
              id="who-can-use"
              className="font-[family-name:var(--font-display)] text-xl text-foreground mb-3"
            >
              1. Who can use Debrief
            </h2>
            <p className="text-muted">
              Debrief is intended for medical trainees (including residents,
              students, and fellows) and their supervising clinicians at
              accredited medical schools and residency programs. By creating an
              account, you confirm that you are authorized to capture and
              process clinical feedback within your institution.
            </p>
          </section>

          <section aria-labelledby="acceptable-use">
            <h2
              id="acceptable-use"
              className="font-[family-name:var(--font-display)] text-xl text-foreground mb-3"
            >
              2. Acceptable use
            </h2>
            <p className="text-muted">You agree to use Debrief only for:</p>
            <ul className="list-disc pl-5 mt-3 space-y-2 text-muted">
              <li>
                Capturing verbal feedback from supervising clinicians after
                clinical encounters.
              </li>
              <li>
                Generating and reviewing competency-based assessments for your
                own training record.
              </li>
              <li>
                Exporting assessments into your program&rsquo;s official
                assessment system.
              </li>
            </ul>
            <p className="mt-4 text-muted">You agree NOT to:</p>
            <ul className="list-disc pl-5 mt-3 space-y-2 text-muted">
              <li>Record individuals without their knowledge or consent.</li>
              <li>
                Use the platform to capture patient conversations or any data
                beyond what is needed for the assessment.
              </li>
              <li>
                Attempt to reverse-engineer, scrape, or misuse the platform.
              </li>
              <li>
                Share account credentials with others.
              </li>
            </ul>
          </section>

          <section aria-labelledby="ip">
            <h2
              id="ip"
              className="font-[family-name:var(--font-display)] text-xl text-foreground mb-3"
            >
              3. Intellectual property of generated assessments
            </h2>
            <p className="text-muted">
              Assessments generated by Debrief belong to you, the trainee. You
              own the structured competency data, transcripts, and exported
              documents produced from your recordings. Whitecoat Prep does not
              claim any rights to your assessment content.
            </p>
            <p className="mt-4 text-muted">
              The Debrief platform, software, and design remain the
              intellectual property of Whitecoat Prep.
            </p>
          </section>

          <section aria-labelledby="no-medical-advice">
            <h2
              id="no-medical-advice"
              className="font-[family-name:var(--font-display)] text-xl text-foreground mb-3"
            >
              4. No medical advice, no clinical liability
            </h2>
            <p className="text-muted">
              Debrief is an assessment documentation tool. It does not provide
              medical advice, clinical guidance, or recommendations about
              patient care. No output from Debrief should be used to make
              clinical decisions.
            </p>
            <p className="mt-4 text-muted">
              Whitecoat Prep is not liable for any clinical decisions made in
              reliance on, or connection with, content generated by this
              platform.
            </p>
          </section>

          <section aria-labelledby="termination">
            <h2
              id="termination"
              className="font-[family-name:var(--font-display)] text-xl text-foreground mb-3"
            >
              5. Account termination
            </h2>
            <p className="text-muted">
              You may delete your account at any time. Upon deletion, all
              associated data (recordings, transcripts, assessments) will be
              permanently removed within 30 days.
            </p>
            <p className="mt-4 text-muted">
              We reserve the right to suspend or terminate accounts that
              violate these terms, with or without notice.
            </p>
          </section>

          <section aria-labelledby="governing-law">
            <h2
              id="governing-law"
              className="font-[family-name:var(--font-display)] text-xl text-foreground mb-3"
            >
              6. Governing law
            </h2>
            <p className="text-muted">
              These terms are governed by and construed in accordance with the
              laws of British Columbia, Canada, without regard to conflict of
              law principles. Any disputes will be resolved in the courts of
              British Columbia.
            </p>
          </section>

          <section aria-labelledby="changes-terms">
            <h2
              id="changes-terms"
              className="font-[family-name:var(--font-display)] text-xl text-foreground mb-3"
            >
              7. Changes to these terms
            </h2>
            <p className="text-muted">
              We may update these terms from time to time. When we do, we will
              notify you by email and update the date at the top of this page.
              Continued use of Debrief after changes take effect constitutes
              acceptance of the new terms.
            </p>
          </section>

          <section
            aria-labelledby="contact-terms"
            className="rounded-[var(--radius-lg)] border border-border bg-surface p-6"
          >
            <h2
              id="contact-terms"
              className="font-[family-name:var(--font-display)] text-lg text-foreground mb-2"
            >
              Questions?
            </h2>
            <p className="text-muted text-sm">
              Email us at{" "}
              <a
                href="mailto:legal@whitecoatprep.com"
                className="text-accent underline underline-offset-2 hover:text-accent-hover"
              >
                legal@whitecoatprep.com
              </a>
              .
            </p>
          </section>
        </div>
      </main>

      <SiteFooter />
    </div>
  );
}
